// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserLine } from "./UserLine.js";

export type CanvasState = Array<UserLine>;
