// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coordinate } from "./Coordinate.js";
import type { Line } from "./Line.js";

export type ClientEvent = { "cursor_position": Coordinate } | { "draw_line": Line } | { "username_update": string };
