// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coordinate } from "./Coordinate.js";
import type { PencilColor } from "./PencilColor.js";
import type { PencilThickness } from "./PencilThickness.js";

export type Line = { from: Coordinate, to: Coordinate, thickness: PencilThickness, color: PencilColor, };
