// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PencilColor = "red" | "blue" | "green" | "brown" | "yellow" | "pink" | "black" | "grey";
