// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasState } from "./CanvasState.js";
import type { User } from "./User.js";

export type Room = { uid: string, users: Array<User>, public: boolean, state: CanvasState, };
